spring:
  profiles:
    active:
      - dev
---
  spring:
    profiles: dev # 开发环境
    application: microservicecloud-config-qfzy-dev
---
  spring:
    profiles: test # 测试环境
    application: microservicecloud-config-qfzy-test
